version: 2
jobs:
  build:
    working_directory: ~/src/edx-platform
    parallelism: 4
    shell: /bin/bash --login
    environment:
      CIRCLE_TEST_REPORTS: /tmp/circleci-results
      COVERALLS_PARALLEL: true
      NO_PREREQ_INSTALL: false
    docker:
    - image: 'circleci/buildpack-deps:xenial-scm-browsers'
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dep-{{ .Branch }}-
        - v1-dep-master-
        - v1-dep-
    - run: echo 'export TRAVIS_JOB_ID="${CIRCLE_BUILD_NUM}"' >> $BASH_ENV
    - run: curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
    - run: sudo apt-get update
    - run: sudo apt-get upgrade
    - run: mkdir -p ~/.cache || true
    - run:
        command: |
          if ! [[ -d ~/.cache/apt/archives ]]; then
            sudo apt install -y --download-only libssl-dev libffi-dev python-pip libsqlite3-dev nodejs
            while read package; do
              sudo apt install -y --download-only "${package}" || true
            done <requirements/system/ubuntu/apt-packages.txt
            sudo cp -R /var/cache/apt ~/.cache/
            sudo chown -R ${USER}:${USER} ~/.cache/apt
          fi
    - run: find ~/.cache/apt/archives -name '*.deb' -print0 | xargs -0 sudo dpkg -i
    - run: sudo service mongodb start || true
    - run: npm install eslint-config-edx eslint-config-edx-es5
    - run: npm install
    - run: test -e ~/.cache/venv/edxapp || virtualenv ~/.cache/venv/edxapp
    - run: echo 'source ~/.cache/venv/edxapp/bin/activate' >> $BASH_ENV
    - run: pip install setuptools
    - run: pip install --exists-action w -r requirements/edx/testing.txt
    - run: pip install coveralls==1.0
    - run: pip freeze
    - save_cache:
        key: v1-dep-{{ .Branch }}-{{ epoch }}
        paths:
        - ~/.cache/apt
        - ~/.cache/pip
        - ~/.cache/venv
        - ./node_modules
    - run:
        command: ./scripts/all-tests.sh
        no_output_timeout: 900s
    - run:
        name: if [ -z $COVERALLS_REPO_TOKEN ]; then echo "Coveralls token not defined."; else coveralls; fi
        command: if [ -z $COVERALLS_REPO_TOKEN ]; then echo "Coveralls token not defined."; else coveralls || true; fi
        when: on_success
    - store_test_results:
        path: /tmp/circleci-results
    - store_artifacts:
        path: reports/.coverage
